/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GameImport } from './routes/game'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as GameIndexImport } from './routes/game.index'
import { Route as LayoutLobbyImport } from './routes/_layout.lobby_'
import { Route as LayoutLobbyCharacterImport } from './routes/_layout.lobby.character'
import { Route as LayoutLobbyCharacterSubraceImport } from './routes/_layout.lobby.character.subrace'
import { Route as LayoutLobbyCharacterRaceImport } from './routes/_layout.lobby.character.race'
import { Route as LayoutLobbyCharacterOriginImport } from './routes/_layout.lobby.character.origin'
import { Route as LayoutLobbyCharacterLoreImport } from './routes/_layout.lobby.character.lore'
import { Route as LayoutLobbyCharacterClassImport } from './routes/_layout.lobby.character.class'
import { Route as LayoutLobbyCharacterBackgroundImport } from './routes/_layout.lobby.character.background'
import { Route as LayoutLobbyCharacterAbilitiesImport } from './routes/_layout.lobby.character.abilities'

// Create/Update Routes

const GameRoute = GameImport.update({
  path: '/game',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GameIndexRoute = GameIndexImport.update({
  path: '/',
  getParentRoute: () => GameRoute,
} as any)

const LayoutLobbyRoute = LayoutLobbyImport.update({
  path: '/lobby',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLobbyCharacterRoute = LayoutLobbyCharacterImport.update({
  path: '/lobby/character',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLobbyCharacterSubraceRoute =
  LayoutLobbyCharacterSubraceImport.update({
    path: '/subrace',
    getParentRoute: () => LayoutLobbyCharacterRoute,
  } as any)

const LayoutLobbyCharacterRaceRoute = LayoutLobbyCharacterRaceImport.update({
  path: '/race',
  getParentRoute: () => LayoutLobbyCharacterRoute,
} as any)

const LayoutLobbyCharacterOriginRoute = LayoutLobbyCharacterOriginImport.update(
  {
    path: '/origin',
    getParentRoute: () => LayoutLobbyCharacterRoute,
  } as any,
)

const LayoutLobbyCharacterLoreRoute = LayoutLobbyCharacterLoreImport.update({
  path: '/lore',
  getParentRoute: () => LayoutLobbyCharacterRoute,
} as any)

const LayoutLobbyCharacterClassRoute = LayoutLobbyCharacterClassImport.update({
  path: '/class',
  getParentRoute: () => LayoutLobbyCharacterRoute,
} as any)

const LayoutLobbyCharacterBackgroundRoute =
  LayoutLobbyCharacterBackgroundImport.update({
    path: '/background',
    getParentRoute: () => LayoutLobbyCharacterRoute,
  } as any)

const LayoutLobbyCharacterAbilitiesRoute =
  LayoutLobbyCharacterAbilitiesImport.update({
    path: '/abilities',
    getParentRoute: () => LayoutLobbyCharacterRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/game': {
      preLoaderRoute: typeof GameImport
      parentRoute: typeof rootRoute
    }
    '/_layout/lobby': {
      preLoaderRoute: typeof LayoutLobbyImport
      parentRoute: typeof LayoutImport
    }
    '/game/': {
      preLoaderRoute: typeof GameIndexImport
      parentRoute: typeof GameImport
    }
    '/_layout/lobby/character': {
      preLoaderRoute: typeof LayoutLobbyCharacterImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/lobby/character/abilities': {
      preLoaderRoute: typeof LayoutLobbyCharacterAbilitiesImport
      parentRoute: typeof LayoutLobbyCharacterImport
    }
    '/_layout/lobby/character/background': {
      preLoaderRoute: typeof LayoutLobbyCharacterBackgroundImport
      parentRoute: typeof LayoutLobbyCharacterImport
    }
    '/_layout/lobby/character/class': {
      preLoaderRoute: typeof LayoutLobbyCharacterClassImport
      parentRoute: typeof LayoutLobbyCharacterImport
    }
    '/_layout/lobby/character/lore': {
      preLoaderRoute: typeof LayoutLobbyCharacterLoreImport
      parentRoute: typeof LayoutLobbyCharacterImport
    }
    '/_layout/lobby/character/origin': {
      preLoaderRoute: typeof LayoutLobbyCharacterOriginImport
      parentRoute: typeof LayoutLobbyCharacterImport
    }
    '/_layout/lobby/character/race': {
      preLoaderRoute: typeof LayoutLobbyCharacterRaceImport
      parentRoute: typeof LayoutLobbyCharacterImport
    }
    '/_layout/lobby/character/subrace': {
      preLoaderRoute: typeof LayoutLobbyCharacterSubraceImport
      parentRoute: typeof LayoutLobbyCharacterImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    LayoutLobbyRoute,
    LayoutLobbyCharacterRoute.addChildren([
      LayoutLobbyCharacterAbilitiesRoute,
      LayoutLobbyCharacterBackgroundRoute,
      LayoutLobbyCharacterClassRoute,
      LayoutLobbyCharacterLoreRoute,
      LayoutLobbyCharacterOriginRoute,
      LayoutLobbyCharacterRaceRoute,
      LayoutLobbyCharacterSubraceRoute,
    ]),
  ]),
  GameRoute.addChildren([GameIndexRoute]),
])

/* prettier-ignore-end */
